[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.icons]
command = "cargo"
args = ["run", "--bin", "icons"]

[tasks.build]
command = "yarn"
args = ["run", "build"]
dependencies = ["icons"]

[tasks.ext-lint]
command = "yarn"
args = ["run", "lint:ext"]
dependencies = ["build"]

[tasks.bundle]
command = "yarn"
args = ["run", "web-ext", "build", "-s", "../../dist"]
dependencies = ["build"]