[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.icons]
command = "cargo"
args = ["run", "--bin", "icons"]

[tasks.build]
dependencies = ["icons"]
command = "yarn"
args = ["run", "build"]

[tasks.ext-lint]
dependencies = ["build"]
command = "yarn"
args = ["run", "lint:ext"]

[tasks.bundle]
dependencies = ["build"]
command = "yarn"
args = ["run", "web-ext", "build", "-s", "dist"]