[package]
name = "icons"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"] }
dunce = "1.0.2"
image = "0.24.2"
rayon = "1.5.3"
